language: node_js
node_js:
- '4.2'
before_script:
- npm install -g gulp
script: gulp
deploy:
  skip_cleanup: true
  provider: npm
  email: odspnpm@microsoft.com
  api_key:
    secure: 0sCS748+bJVFBW60KE305ANz5FpDA3G6r7HnTxJO6Zsx8miRbQj6aDGKnqFa0Lf9h2sBYzCDxYM75ZL+ZoR7JN9lQS6UhqMPK+PhT6V0EH4wy1WXTzEtqFm9y3HgcsNyD8dj84JbzzadjQLFX0POXoA6LvGIhWglmcX40rZrcQu1/fITX5899DcanQtqUxU3BQnKIdyUg+vqXb9zc8iCF0JqyeeXBW8xIJkBrCGbgJrnIevnEo0P7Q2fJEM4T87CxtkztyySPEDhVCioBQB0LreRQa/hJUiuDzEPX/s9OIAqWYkVdVi/d9XC7B8rdjEQTLuU0wOOqk2v33q6OJRvWWSTcKXRaXQ4rnVTqYGP2G4LPa3ov+/e6Y2PRI+OCgV9/rDRP7U8EjiMmfex14WA+QHVW9hhkbv4gIOZ5A9T9cHIuzX8ne5jnv4g1rj7j9GgzcrHcxvPYyc/aUXzHD7G8//XYrE5PoW0Lj7kNdsIDjVcu+fKe0V9mHwtwjdtkZljDhIXKiAg9yLoEcYaQKbYh638ah7d0nrFCJzlOtj4AtXjfghuI9yYrbaJk2E+2c1rLGjrmmJEOQO+vLGfM3LFEEpcgvQPb7MBzA0UUbB3bg9ZsQZMY8kedHZV+UhWnuM40kN9Rg7UmS8oYS7YIxSdDEDUbHI1BIg3mgb5ZLVgXrg=
  on:
    tags: true
    repo: Microsoft/gulp-core-build
